name: Deploy to Azure Web Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: voxelbox-app    # Replace with your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: '.'     # Path to your app files
  NODE_VERSION: '18'                 # Node.js version

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run type-check

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Create deployment artifact
      run: |
        # Create a zip file with necessary files for deployment
        zip -r deployment.zip .next public package.json package-lock.json next.config.js startup.sh
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: voxelbox-app
        path: deployment.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: voxelbox-app

    - name: Extract artifact
      run: unzip deployment.zip

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}